# Generated by Django 5.2.6 on 2025-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_candidate_full_name_alter_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
